compliance-collector:
  platforms:
    instances:
      aws:
        - name: "aws-production-account"
          properties:
            region: "us-east-1"
        - name: "aws-development-account"
          properties:
            region: "eu-west-2"
      vmware:
        - name: "vcenter-main-dc"
          properties:
            url: "https://vcenter1.example.com/sdk"
        - name: "vcenter-dr-site"
          properties:
            url: "https://vcenter2.example.com/sdk"
      kubernetes:
        - name: "prod-cluster-eks"
          properties:
            kubeconfig: "/path/to/secure/eks.kubeconfig"
            context: "eks-prod"
        - name: "dev-cluster-k3s"
          properties:
            kubeconfig: "/path/to/secure/k3s.kubeconfig"
            context: "default"
